[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Make sure Decap CMS works when visiting /admin (and nested routes)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
